### ISSUE TITLE
AGPL-3.0 Violation

### ISSUE THREAD

**Issue by bookchin** [internxt/Bridge#1]
Hi there, original author of this package here. You may not be aware, but changes you have made are in violation of the license terms. Specifically the removal of the original copyright notice located in the README.

I am not a lawyer, but I am well acquainted with the terms of the AGPL (I selected the license for this and the other Storj packages). From looking at the modifications made, it is clear that you need to do the following:

* Restore the original copyright notice for Storj Labs
* Add an additional copyright notice for yourself and list all major modifications made for the derivative work

Additionally, I personally ask that you amend the `author` field of the `package.json` where you have left me as the author but replaced my email address with an xcloud.io TLD which implies my affiliation with this project. 

I am sure these changes were made with no ill intent, so please consider this a friendly notification. Happy hacking!

**Comment by idostanic** [comment]
Hello! Internxt dev team here 🙂 nice to e-meet you! Sure thing, during the
weekend we'll restore the original copyright notice for Storj Labs and
write an additional copyright notice for ourselves and list all major
modifications made for the derivative work. We'll also change the author
field package.json as requested. Thanks a lot for the tips!

**Comment by idostanic** [comment]
It's fixed, I will close the issue now. Thanks for the heads up!
